### ISSUE TITLE
Display not in stock at Amazon

### ISSUE THREAD

**Issue by amy-langley** [drcode/lisperati-1000-diy#2]
I was looking into acquiring the components for this guide and I noticed that the amazon link for the display indicates that they don't have any and don't know when they'll get any again. I don't want to be a shill so I'm not including a link, but I searched on AliExpress and was able to find several vendors offering it, so it may be worth updating that section of the guide. :)

**Comment by drcode** [comment]
Thanks Amy, I will update the docs when I can
